name: app

type: php:7.4

runtime:
    extensions:
        - apcu
        - mbstring
        - sodium
        - ctype
        - iconv
        

#variables:
#    php:
#        # uncomment on PHP 7.4+, needs Symfony 4.4.14+, 5.1.6+, or 5.2+
#        #opcache.preload: /app/src/.preload.php

build:
    flavor: none

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"

disk: 512

mounts:
    "/var": { source: local, source_path: var }

hooks:
    build: |
        set -x -e

        curl -s https://get.symfony.com/cloud/configurator | (>&2 bash)
        
        (>&2 symfony-build)

    deploy: |
        set -x -e

        (>&2 symfony-deploy)
